### ISSUE TITLE
Managers should be able to comment on reports

### ISSUE THREAD

**Issue by thinkinginmath** [stack360/statusreport#37]
Sometimes an employee asks questions on the status report. 

A manager should be able to add comments on the status report

1. An email will be sent
2. A comment object will be created and associated with the report
3. More comments can be added later. Each comment is a separate object.

**Comment by xichengc** [comment]
Fixed by commit: https://github.com/stack360/statusreport/commit/417e481476ae653cbf681cd2b8f3c52c60ba332b

**Comment by xichengc** [comment]
Wrong commit number, the correct number is: https://github.com/stack360/statusreport/commit/13924a83acb8928928c42e3685e9fd05effe0791
